### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [Coin2Play/c2pcore#6]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

**Comment by MotoAcidic** [comment]
Please display your legal copyright backing that you actually have anything to do with the pivx project. We will work according if you can verify that you are not someone you claim not to be. Also name the files you wish pivx to listed under. And hope you actually single out other projects this trolling fashion you are displaying. Also there is no fork from displayed on this source.

**Comment by Iconoclasta** [comment]
Yep. I think you'll find most of your concerns addressed here: https://github.com/Dystem/dystem-core/issues/2

in short, I have noticed you are infringing on PIVX copyright (eg deleting the project's name from `COPYING`).
I have hence decided to open this issue out of courtesy. It is not to be intended as legal discourse. Should you prefer to proceed to such measures I will notify PIVX's legal team.

**Comment by MotoAcidic** [comment]
So you go around to project and seek out copyright stuff....... Seems kinda petty really. Will add them but you need to specifiy what files and where since the project is not shown as forked from so it could have been forked from another live chain other then pivx and they should be the ones you post issues on.

**Comment by Iconoclasta** [comment]
Love how you're the culprit but somehow I'm demonized for pointing it out. Standardize your code or an official DMCA notice will be filed.

**Comment by Coin2Play** [comment]
Iconoclasta - Our code is forked from Lightpaycoin, and we have added copyright to the main sections of the code. You can check the Lightpaycoin source code at https://github.com/lpcproject/LightPayCoin
We have just use the code base from lightpaycoin and add the copyright from their code base without updating anything in their code base which we have not touched. If you believe they have not addressed a copyright for PIVX in their code base, you need to address this with lpc. Thank you.

**Comment by Iconoclasta** [comment]
Hey. The "if others are doing it we should be doing it as well" argument doesn't quite stand. I will be opening a license violation courtesy notice on Lightpay soon thanks for pointing them to me.

This although does not change the fact your project is infringing on PIVX's license. It is not true you haven't changed anything since LightPay (eg adding your project's name to this license list: https://github.com/Coin2Play/c2pcore/blob/master/src/chainparams.cpp )
Please amend this issue ASAP.

**Comment by MotoAcidic** [comment]
The license doesnt even point to any of those projects you say it is mentioned in Chainparams.cpp
https://opensource.org/licenses/mit-license.php
https://opensource.org/licenses/OSL-3.0

Post this license you are referencing.

**Comment by Iconoclasta** [comment]
@MotoAcidic I do not know what that means. 
The issue remains unsolved.

**Comment by Fuzzbawls** [comment]
The issue with LPC's codebase has already been addressed and resolved back at the end of July (https://github.com/lpcproject/LightPayCoin/issues/7).

Regardless, Coin2Play is still responsible for ensuring that they are not violating any copyrights or license terms. @Iconoclasta has already pointed out that the offending file is `COPYING` in the root of the source tree.

**Comment by MotoAcidic** [comment]
He never made it clear that was a file that needed it changed but rather referenced chainparams.cpp.
If he would have worded it better that it needs to be fixed in this file "COPYING" it would have made it much clearer to everyone since the was he worded it he wanted all files.
Will do a pull to get this fixed.

**Comment by MotoAcidic** [comment]
#7  Just made the pull request @Fuzzbawls

**Comment by Coin2Play** [comment]
@Iconoclasta @Fuzzbawls Thanks for the info. We have updated the file. We never knew the missing info, as we forked off lightpaycoin code base. Thanks for explaining. It has now been addressed quickly. Thanks again.
